mnist-nfl-dp-val-warm0-direct-it10-eps600-lba1e-05-dlg-updates:
  B: 4
  clip: 10
  clipDP: 500
  cost_fn: sim
  distort: nfl
  dlg: 'true'
  dlg_attack_epochs: 0-1-2
  dlg_img_init: /demo/xxx/mnist.dlg.init
  dlg_iter: 10
  dlg_lr: 0.1
  dlg_optim: adam
  ds_name: mnist
  early_stop_rounds: 50
  eps: 600
  global_epoch: 3
  data_per_client: 12
  gpu: 0
  known_grad: updates
  label_guess: 'false'
  lba: 1.0e-05
  local_batch_iter: 1
  lr: 0.1
  model_optim: sgd
  n_clients: 4
  nfl_it: 10
  opt_target: val
  out_dir: runs_debug
  privacy: dp
  shuffle: 'false'
  task_id: mnist-nfl-dp-val-warm0-direct-it10-eps600-lba1e-05-dlg-updates
  tv_lambda: 1.0e-06
  u_loss_type: direct
  warm_up_rounds: 0
  zeta: 0.1